apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernete-pod1
  labels:
    app: pod1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod1
  template:
    metadata:
      labels:
        app: pod1 
    spec:
      containers:
      - name: nodeserver
        image: jdr1099/kubernete-pod1:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: pod1-service
spec:
  selector:
    app: pod1 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110