apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernete-pod1
  labels:
    app: pod1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod1
  template:
    metadata:
      labels:
        app: pod1 
    spec:
      containers:
      - name: nodeserver
        image: jdr1099/kubernete-pod1:latest
        ports:
        - containerPort: 3000
        resources:
            requests:
              memory: "250Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "1000m"