apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernete-pod2
  labels:
    app: pod2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod2
  template:
    metadata:
      labels:
        app: pod2 
    spec:
      containers:
      - name: nodeserver
        image: jdr1099/kubernete-pod2:latest
        ports:
        - containerPort: 3001
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: pod2-service
spec:
  selector:
    app: pod2 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 3000
    nodePort: 31111