apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernete-pod2
  labels:
    app: pod2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod2
  template:
    metadata:
      labels:
        app: pod2 
    spec:
      containers:
      - name: nodeserver
        image: jdr1099/kubernete-pod2:latest
        ports:
        - containerPort: 3001
        resources:
            requests:
              memory: "250Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "1000m"